// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/reporter/dbproto/dbproto.proto
// DO NOT EDIT!

/*
Package dbproto is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/reporter/dbproto/dbproto.proto

It has these top-level messages:
	ComponentList
	Component
	State
	RemoteList
	Remote
	RemoteConfig
	RemoteState
*/
package dbproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import stream "github.com/fuserobotics/statestream"
import remote "github.com/fuserobotics/reporter/remote"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ComponentList struct {
	ComponentName []string `protobuf:"bytes,1,rep,name=component_name,json=componentName" json:"component_name,omitempty"`
}

func (m *ComponentList) Reset()                    { *m = ComponentList{} }
func (m *ComponentList) String() string            { return proto.CompactTextString(m) }
func (*ComponentList) ProtoMessage()               {}
func (*ComponentList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Component struct {
	StateName []string `protobuf:"bytes,1,rep,name=state_name,json=stateName" json:"state_name,omitempty"`
}

func (m *Component) Reset()                    { *m = Component{} }
func (m *Component) String() string            { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()               {}
func (*Component) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type State struct {
	SnapshotTimestamp []int64        `protobuf:"varint,1,rep,packed,name=snapshot_timestamp,json=snapshotTimestamp" json:"snapshot_timestamp,omitempty"`
	AllTimestamp      []int64        `protobuf:"varint,2,rep,packed,name=all_timestamp,json=allTimestamp" json:"all_timestamp,omitempty"`
	StreamConfig      *stream.Config `protobuf:"bytes,3,opt,name=stream_config,json=streamConfig" json:"stream_config,omitempty"`
}

func (m *State) Reset()                    { *m = State{} }
func (m *State) String() string            { return proto.CompactTextString(m) }
func (*State) ProtoMessage()               {}
func (*State) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *State) GetStreamConfig() *stream.Config {
	if m != nil {
		return m.StreamConfig
	}
	return nil
}

type RemoteList struct {
	RemoteId []string `protobuf:"bytes,1,rep,name=remote_id,json=remoteId" json:"remote_id,omitempty"`
}

func (m *RemoteList) Reset()                    { *m = RemoteList{} }
func (m *RemoteList) String() string            { return proto.CompactTextString(m) }
func (*RemoteList) ProtoMessage()               {}
func (*RemoteList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Remote struct {
	Id           string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Config       *RemoteConfig              `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
	State        []*RemoteState             `protobuf:"bytes,3,rep,name=state" json:"state,omitempty"`
	StreamConfig *remote.RemoteStreamConfig `protobuf:"bytes,4,opt,name=stream_config,json=streamConfig" json:"stream_config,omitempty"`
}

func (m *Remote) Reset()                    { *m = Remote{} }
func (m *Remote) String() string            { return proto.CompactTextString(m) }
func (*Remote) ProtoMessage()               {}
func (*Remote) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Remote) GetConfig() *RemoteConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Remote) GetState() []*RemoteState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Remote) GetStreamConfig() *remote.RemoteStreamConfig {
	if m != nil {
		return m.StreamConfig
	}
	return nil
}

type RemoteConfig struct {
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
}

func (m *RemoteConfig) Reset()                    { *m = RemoteConfig{} }
func (m *RemoteConfig) String() string            { return proto.CompactTextString(m) }
func (*RemoteConfig) ProtoMessage()               {}
func (*RemoteConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type RemoteState struct {
	ComponentName string `protobuf:"bytes,1,opt,name=component_name,json=componentName" json:"component_name,omitempty"`
	StateName     string `protobuf:"bytes,2,opt,name=state_name,json=stateName" json:"state_name,omitempty"`
}

func (m *RemoteState) Reset()                    { *m = RemoteState{} }
func (m *RemoteState) String() string            { return proto.CompactTextString(m) }
func (*RemoteState) ProtoMessage()               {}
func (*RemoteState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*ComponentList)(nil), "dbproto.ComponentList")
	proto.RegisterType((*Component)(nil), "dbproto.Component")
	proto.RegisterType((*State)(nil), "dbproto.State")
	proto.RegisterType((*RemoteList)(nil), "dbproto.RemoteList")
	proto.RegisterType((*Remote)(nil), "dbproto.Remote")
	proto.RegisterType((*RemoteConfig)(nil), "dbproto.RemoteConfig")
	proto.RegisterType((*RemoteState)(nil), "dbproto.RemoteState")
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/reporter/dbproto/dbproto.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x52, 0xd1, 0x8a, 0x9b, 0x40,
	0x14, 0x45, 0x6d, 0xd2, 0x78, 0x13, 0x43, 0x3b, 0xb4, 0x10, 0x2c, 0x85, 0x20, 0x94, 0xda, 0x40,
	0xb4, 0x4d, 0x20, 0x4f, 0x85, 0x42, 0xf3, 0x54, 0x28, 0xfb, 0x60, 0xf6, 0x5d, 0x46, 0x9d, 0x24,
	0x03, 0x8e, 0x23, 0x33, 0x93, 0xfd, 0x96, 0xfd, 0x90, 0xfd, 0xc0, 0x65, 0x67, 0xd4, 0x88, 0xbb,
	0xcb, 0xbe, 0x38, 0xdc, 0x33, 0xe7, 0x78, 0xef, 0x39, 0x77, 0x60, 0x77, 0xa2, 0xea, 0x7c, 0xc9,
	0xa2, 0x9c, 0xb3, 0xf8, 0x78, 0x91, 0x44, 0xf0, 0x8c, 0x2b, 0x9a, 0xcb, 0x58, 0x90, 0x9a, 0x0b,
	0x45, 0x44, 0x5c, 0x64, 0xb5, 0xe0, 0x8a, 0xb7, 0x67, 0xa4, 0xbf, 0xe8, 0x7d, 0x53, 0xfa, 0x3f,
	0x5f, 0xfb, 0x81, 0x54, 0x58, 0x11, 0xa9, 0x04, 0xc1, 0x2c, 0xce, 0x79, 0x75, 0xa4, 0x27, 0x23,
	0xf5, 0x7f, 0xbf, 0xd9, 0x52, 0x10, 0xc6, 0x15, 0x69, 0x8e, 0xb5, 0x24, 0xe2, 0x8e, 0xe6, 0xc4,
	0xa8, 0x83, 0x1d, 0x78, 0x7b, 0xce, 0x6a, 0x5e, 0x91, 0x4a, 0xfd, 0xa7, 0x52, 0xa1, 0x6f, 0x30,
	0xcf, 0x5b, 0x20, 0xad, 0x30, 0x23, 0x0b, 0x6b, 0xe9, 0x84, 0x6e, 0xe2, 0x75, 0xe8, 0x0d, 0x66,
	0x24, 0x58, 0x81, 0xdb, 0xe9, 0xd0, 0x57, 0x00, 0x3d, 0x5e, 0x9f, 0xef, 0x6a, 0x44, 0x73, 0xef,
	0x2d, 0x18, 0x1d, 0x9e, 0x2a, 0xf4, 0x0b, 0x90, 0xac, 0x70, 0x2d, 0xcf, 0x5c, 0xa5, 0x8a, 0x32,
	0x22, 0x15, 0x66, 0xb5, 0x16, 0x38, 0x7f, 0xed, 0x0f, 0x56, 0xf2, 0xb1, 0xbd, 0xbd, 0x6d, 0x2f,
	0xd1, 0x77, 0xf0, 0x70, 0x59, 0xf6, 0xd8, 0x76, 0xc7, 0x9e, 0xe1, 0xb2, 0xbc, 0x12, 0xb7, 0xe0,
	0x99, 0x78, 0x52, 0x13, 0xcf, 0xc2, 0x59, 0x5a, 0xe1, 0x74, 0x33, 0x8f, 0x0c, 0x1a, 0xed, 0x35,
	0x9a, 0xcc, 0x4c, 0x69, 0xaa, 0xe0, 0x07, 0x40, 0xa2, 0x63, 0xd1, 0xde, 0xbf, 0x80, 0x6b, 0x42,
	0x4a, 0x69, 0xd1, 0xd8, 0x98, 0x18, 0xe0, 0x5f, 0x11, 0x3c, 0x58, 0x30, 0x36, 0x5c, 0x34, 0x07,
	0x5b, 0x13, 0xac, 0xd0, 0x4d, 0x6c, 0x5a, 0xa0, 0x35, 0x8c, 0x9b, 0x9e, 0xb6, 0xee, 0xf9, 0x39,
	0x6a, 0xb7, 0x6b, 0x04, 0x4d, 0xeb, 0x86, 0x84, 0x56, 0x30, 0xd2, 0xe1, 0x2c, 0x9c, 0xa5, 0x13,
	0x4e, 0x37, 0x9f, 0x06, 0x6c, 0x1d, 0x55, 0x62, 0x28, 0xe8, 0xcf, 0xd0, 0xd5, 0x3b, 0xdd, 0xc1,
	0x8f, 0xcc, 0x5c, 0x9d, 0xe4, 0xea, 0x69, 0xe0, 0x70, 0x05, 0xb3, 0xfe, 0x10, 0xc8, 0x87, 0x09,
	0xa9, 0x8a, 0x9a, 0xd3, 0x4a, 0x35, 0x0e, 0xba, 0x3a, 0x38, 0xc0, 0xb4, 0x37, 0xc2, 0x8b, 0x4f,
	0xc1, 0x7a, 0xf6, 0x14, 0x06, 0xdb, 0xb7, 0x35, 0xe5, 0xba, 0xfd, 0x6c, 0xac, 0xbd, 0x6d, 0x1f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x37, 0x33, 0xb9, 0x1b, 0x03, 0x00, 0x00,
}
