// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/reporter/remote/remote-service.proto
// DO NOT EDIT!

/*
Package remote is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/reporter/remote/remote-service.proto

It has these top-level messages:
	RemoteStreamEntry
	RemoteStreamConfig
	RequestContext
	GetRemoteConfigRequest
	GetRemoteConfigResponse
	PushStreamEntryRequest
	PushStreamEntryResponse
*/
package remote

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RemoteStreamEntry struct {
	Timestamp int64  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	EntryType int32  `protobuf:"varint,2,opt,name=entry_type,json=entryType" json:"entry_type,omitempty"`
	JsonData  string `protobuf:"bytes,3,opt,name=json_data,json=jsonData" json:"json_data,omitempty"`
}

func (m *RemoteStreamEntry) Reset()                    { *m = RemoteStreamEntry{} }
func (m *RemoteStreamEntry) String() string            { return proto.CompactTextString(m) }
func (*RemoteStreamEntry) ProtoMessage()               {}
func (*RemoteStreamEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RemoteStreamConfig struct {
	Crc32 int32 `protobuf:"varint,1,opt,name=crc32" json:"crc32,omitempty"`
}

func (m *RemoteStreamConfig) Reset()                    { *m = RemoteStreamConfig{} }
func (m *RemoteStreamConfig) String() string            { return proto.CompactTextString(m) }
func (*RemoteStreamConfig) ProtoMessage()               {}
func (*RemoteStreamConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RequestContext struct {
	HostIdentifier string `protobuf:"bytes,1,opt,name=host_identifier,json=hostIdentifier" json:"host_identifier,omitempty"`
	ComponentId    string `protobuf:"bytes,2,opt,name=component_id,json=componentId" json:"component_id,omitempty"`
	StateId        string `protobuf:"bytes,3,opt,name=state_id,json=stateId" json:"state_id,omitempty"`
}

func (m *RequestContext) Reset()                    { *m = RequestContext{} }
func (m *RequestContext) String() string            { return proto.CompactTextString(m) }
func (*RequestContext) ProtoMessage()               {}
func (*RequestContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetRemoteConfigRequest struct {
	Context *RequestContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
}

func (m *GetRemoteConfigRequest) Reset()                    { *m = GetRemoteConfigRequest{} }
func (m *GetRemoteConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRemoteConfigRequest) ProtoMessage()               {}
func (*GetRemoteConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetRemoteConfigRequest) GetContext() *RequestContext {
	if m != nil {
		return m.Context
	}
	return nil
}

type GetRemoteConfigResponse struct {
	Config *RemoteStreamConfig `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
}

func (m *GetRemoteConfigResponse) Reset()                    { *m = GetRemoteConfigResponse{} }
func (m *GetRemoteConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRemoteConfigResponse) ProtoMessage()               {}
func (*GetRemoteConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetRemoteConfigResponse) GetConfig() *RemoteStreamConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type PushStreamEntryRequest struct {
	Context     *RequestContext    `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Entry       *RemoteStreamEntry `protobuf:"bytes,2,opt,name=entry" json:"entry,omitempty"`
	ConfigCrc32 int32              `protobuf:"varint,3,opt,name=config_crc32,json=configCrc32" json:"config_crc32,omitempty"`
}

func (m *PushStreamEntryRequest) Reset()                    { *m = PushStreamEntryRequest{} }
func (m *PushStreamEntryRequest) String() string            { return proto.CompactTextString(m) }
func (*PushStreamEntryRequest) ProtoMessage()               {}
func (*PushStreamEntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PushStreamEntryRequest) GetContext() *RequestContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PushStreamEntryRequest) GetEntry() *RemoteStreamEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type PushStreamEntryResponse struct {
	// If the crc32 provided is wrong, will return config
	Config *RemoteStreamConfig `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
}

func (m *PushStreamEntryResponse) Reset()                    { *m = PushStreamEntryResponse{} }
func (m *PushStreamEntryResponse) String() string            { return proto.CompactTextString(m) }
func (*PushStreamEntryResponse) ProtoMessage()               {}
func (*PushStreamEntryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PushStreamEntryResponse) GetConfig() *RemoteStreamConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func init() {
	proto.RegisterType((*RemoteStreamEntry)(nil), "remote.RemoteStreamEntry")
	proto.RegisterType((*RemoteStreamConfig)(nil), "remote.RemoteStreamConfig")
	proto.RegisterType((*RequestContext)(nil), "remote.RequestContext")
	proto.RegisterType((*GetRemoteConfigRequest)(nil), "remote.GetRemoteConfigRequest")
	proto.RegisterType((*GetRemoteConfigResponse)(nil), "remote.GetRemoteConfigResponse")
	proto.RegisterType((*PushStreamEntryRequest)(nil), "remote.PushStreamEntryRequest")
	proto.RegisterType((*PushStreamEntryResponse)(nil), "remote.PushStreamEntryResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ReporterRemoteService service

type ReporterRemoteServiceClient interface {
	GetRemoteConfig(ctx context.Context, in *GetRemoteConfigRequest, opts ...grpc.CallOption) (*GetRemoteConfigResponse, error)
	PushStreamEntry(ctx context.Context, in *PushStreamEntryRequest, opts ...grpc.CallOption) (*PushStreamEntryResponse, error)
}

type reporterRemoteServiceClient struct {
	cc *grpc.ClientConn
}

func NewReporterRemoteServiceClient(cc *grpc.ClientConn) ReporterRemoteServiceClient {
	return &reporterRemoteServiceClient{cc}
}

func (c *reporterRemoteServiceClient) GetRemoteConfig(ctx context.Context, in *GetRemoteConfigRequest, opts ...grpc.CallOption) (*GetRemoteConfigResponse, error) {
	out := new(GetRemoteConfigResponse)
	err := grpc.Invoke(ctx, "/remote.ReporterRemoteService/GetRemoteConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterRemoteServiceClient) PushStreamEntry(ctx context.Context, in *PushStreamEntryRequest, opts ...grpc.CallOption) (*PushStreamEntryResponse, error) {
	out := new(PushStreamEntryResponse)
	err := grpc.Invoke(ctx, "/remote.ReporterRemoteService/PushStreamEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ReporterRemoteService service

type ReporterRemoteServiceServer interface {
	GetRemoteConfig(context.Context, *GetRemoteConfigRequest) (*GetRemoteConfigResponse, error)
	PushStreamEntry(context.Context, *PushStreamEntryRequest) (*PushStreamEntryResponse, error)
}

func RegisterReporterRemoteServiceServer(s *grpc.Server, srv ReporterRemoteServiceServer) {
	s.RegisterService(&_ReporterRemoteService_serviceDesc, srv)
}

func _ReporterRemoteService_GetRemoteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRemoteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterRemoteServiceServer).GetRemoteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.ReporterRemoteService/GetRemoteConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterRemoteServiceServer).GetRemoteConfig(ctx, req.(*GetRemoteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReporterRemoteService_PushStreamEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushStreamEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterRemoteServiceServer).PushStreamEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remote.ReporterRemoteService/PushStreamEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterRemoteServiceServer).PushStreamEntry(ctx, req.(*PushStreamEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReporterRemoteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remote.ReporterRemoteService",
	HandlerType: (*ReporterRemoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRemoteConfig",
			Handler:    _ReporterRemoteService_GetRemoteConfig_Handler,
		},
		{
			MethodName: "PushStreamEntry",
			Handler:    _ReporterRemoteService_PushStreamEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/reporter/remote/remote-service.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0x41, 0x6f, 0x12, 0x41,
	0x18, 0xcd, 0x96, 0x40, 0xbb, 0x1f, 0xa6, 0xa4, 0xa3, 0x52, 0xc0, 0xaa, 0xb8, 0x17, 0x49, 0x13,
	0x59, 0xa5, 0x27, 0x8d, 0xf1, 0x42, 0x8d, 0xc1, 0xa4, 0x89, 0x19, 0xbd, 0x93, 0x61, 0xf9, 0x80,
	0x31, 0xee, 0xcc, 0x3a, 0xf3, 0x51, 0x25, 0xa6, 0x17, 0xff, 0x82, 0x17, 0x4f, 0x26, 0xfe, 0x26,
	0xff, 0x82, 0x3f, 0xc4, 0xec, 0xcc, 0x52, 0x90, 0xd2, 0x4b, 0x4f, 0x64, 0xdf, 0x3c, 0xbe, 0xf7,
	0xe6, 0xbd, 0x6f, 0xe0, 0xe5, 0x54, 0xd2, 0x6c, 0x3e, 0xea, 0x26, 0x3a, 0x8d, 0x27, 0x73, 0x8b,
	0x46, 0x8f, 0x34, 0xc9, 0xc4, 0xc6, 0x06, 0x33, 0x6d, 0x08, 0x4d, 0x6c, 0x30, 0xd5, 0x84, 0xc5,
	0xcf, 0x13, 0x8b, 0xe6, 0x5c, 0x26, 0xd8, 0xcd, 0x8c, 0x26, 0xcd, 0x2a, 0x1e, 0x6d, 0x1d, 0x4d,
	0xb5, 0x9e, 0x7e, 0xc2, 0x58, 0x64, 0x32, 0x16, 0x4a, 0x69, 0x12, 0x24, 0xb5, 0xb2, 0x9e, 0x15,
	0xa5, 0x70, 0xc0, 0x1d, 0xef, 0x3d, 0x19, 0x14, 0xe9, 0x6b, 0x45, 0x66, 0xc1, 0x8e, 0x20, 0x24,
	0x99, 0xa2, 0x25, 0x91, 0x66, 0x8d, 0xa0, 0x1d, 0x74, 0x4a, 0x7c, 0x05, 0xb0, 0xfb, 0x00, 0x98,
	0xd3, 0x86, 0xb4, 0xc8, 0xb0, 0xb1, 0xd3, 0x0e, 0x3a, 0x65, 0x1e, 0x3a, 0xe4, 0xc3, 0x22, 0x43,
	0x76, 0x0f, 0xc2, 0x8f, 0x56, 0xab, 0xe1, 0x58, 0x90, 0x68, 0x94, 0xda, 0x41, 0x27, 0xe4, 0x7b,
	0x39, 0x70, 0x2a, 0x48, 0x44, 0xc7, 0xc0, 0xd6, 0xe5, 0xfa, 0x5a, 0x4d, 0xe4, 0x94, 0xdd, 0x81,
	0x72, 0x62, 0x92, 0x93, 0x9e, 0xd3, 0x2a, 0x73, 0xff, 0x11, 0x7d, 0x81, 0x7d, 0x8e, 0x9f, 0xe7,
	0x68, 0xa9, 0xaf, 0x15, 0xe1, 0x57, 0x62, 0x8f, 0xa1, 0x36, 0xd3, 0x96, 0x86, 0x72, 0x8c, 0x8a,
	0xe4, 0x44, 0xa2, 0x71, 0xff, 0x08, 0xf9, 0x7e, 0x0e, 0x0f, 0x2e, 0x51, 0xf6, 0x08, 0x6e, 0x25,
	0x3a, 0xcd, 0xb4, 0x42, 0x95, 0xb3, 0x9d, 0xc9, 0x90, 0x57, 0x2f, 0xb1, 0xc1, 0x98, 0x35, 0x61,
	0xcf, 0x92, 0x20, 0xcc, 0x8f, 0xbd, 0xcb, 0x5d, 0xf7, 0x3d, 0x18, 0x47, 0x6f, 0xa1, 0xfe, 0x06,
	0xc9, 0xfb, 0xf4, 0x0e, 0x0b, 0x1f, 0xec, 0x29, 0xec, 0x26, 0xde, 0x8b, 0x13, 0xae, 0xf6, 0xea,
	0x5d, 0x9f, 0x72, 0xf7, 0x7f, 0xa7, 0x7c, 0x49, 0x8b, 0xce, 0xe0, 0xf0, 0xca, 0x2c, 0x9b, 0x69,
	0x65, 0x91, 0xf5, 0xa0, 0x92, 0x38, 0xa4, 0x98, 0xd5, 0x5a, 0xcd, 0xda, 0x4c, 0x88, 0x17, 0xcc,
	0xe8, 0x57, 0x00, 0xf5, 0x77, 0x73, 0x3b, 0x5b, 0x6b, 0xeb, 0xc6, 0xde, 0x58, 0x0c, 0x65, 0x57,
	0x9b, 0x8b, 0xa7, 0xda, 0x6b, 0x6e, 0xd3, 0xf7, 0x12, 0x9e, 0xe7, 0x63, 0xcd, 0x7d, 0x0c, 0x7d,
	0x5d, 0x25, 0x57, 0x57, 0xd5, 0x63, 0x7d, 0x57, 0xda, 0x19, 0x1c, 0x5e, 0xf1, 0x77, 0xf3, 0xfb,
	0xf6, 0x7e, 0xef, 0xc0, 0x5d, 0x5e, 0x6c, 0x7b, 0x41, 0xf3, 0x4b, 0xce, 0x52, 0xa8, 0x6d, 0x04,
	0xcb, 0x1e, 0x2c, 0x07, 0x6e, 0x6f, 0xaf, 0xf5, 0xf0, 0xda, 0x73, 0xef, 0x30, 0x6a, 0x7e, 0xff,
	0xf3, 0xf7, 0xc7, 0xce, 0x6d, 0x76, 0x10, 0x9f, 0x3f, 0x5b, 0xbe, 0x2d, 0x6f, 0x84, 0xfd, 0x0c,
	0xa0, 0xb6, 0x71, 0xb1, 0x95, 0xde, 0xf6, 0x46, 0x56, 0x7a, 0xd7, 0x24, 0x12, 0x9d, 0x3a, 0xbd,
	0x57, 0xd1, 0xf3, 0x35, 0xbd, 0x6f, 0x45, 0x3b, 0xdd, 0xf5, 0x05, 0xbe, 0x58, 0xc1, 0xcb, 0xa5,
	0xbd, 0x88, 0xb3, 0xb9, 0x9d, 0xbd, 0x08, 0x8e, 0x47, 0x15, 0xf7, 0x92, 0x4f, 0xfe, 0x05, 0x00,
	0x00, 0xff, 0xff, 0xc2, 0xc3, 0xf3, 0xe4, 0x2f, 0x04, 0x00, 0x00,
}
