// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/reporter/api/reporter.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import stream "github.com/fuserobotics/statestream"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StateContext struct {
	Component string `protobuf:"bytes,1,opt,name=component" json:"component,omitempty"`
	StateId   string `protobuf:"bytes,2,opt,name=state_id,json=stateId" json:"state_id,omitempty"`
}

func (m *StateContext) Reset()                    { *m = StateContext{} }
func (m *StateContext) String() string            { return proto.CompactTextString(m) }
func (*StateContext) ProtoMessage()               {}
func (*StateContext) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// A state report message
type StateReport struct {
	// Support json formatted report
	JsonState string `protobuf:"bytes,1,opt,name=json_state,json=jsonState" json:"json_state,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *StateReport) Reset()                    { *m = StateReport{} }
func (m *StateReport) String() string            { return proto.CompactTextString(m) }
func (*StateReport) ProtoMessage()               {}
func (*StateReport) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type StateList struct {
	Components []*StateListComponent `protobuf:"bytes,1,rep,name=components" json:"components,omitempty"`
}

func (m *StateList) Reset()                    { *m = StateList{} }
func (m *StateList) String() string            { return proto.CompactTextString(m) }
func (*StateList) ProtoMessage()               {}
func (*StateList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *StateList) GetComponents() []*StateListComponent {
	if m != nil {
		return m.Components
	}
	return nil
}

type StateListComponent struct {
	Name   string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	States []*StateListState `protobuf:"bytes,2,rep,name=states" json:"states,omitempty"`
}

func (m *StateListComponent) Reset()                    { *m = StateListComponent{} }
func (m *StateListComponent) String() string            { return proto.CompactTextString(m) }
func (*StateListComponent) ProtoMessage()               {}
func (*StateListComponent) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *StateListComponent) GetStates() []*StateListState {
	if m != nil {
		return m.States
	}
	return nil
}

type StateListState struct {
	Name   string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Config *stream.Config `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
}

func (m *StateListState) Reset()                    { *m = StateListState{} }
func (m *StateListState) String() string            { return proto.CompactTextString(m) }
func (*StateListState) ProtoMessage()               {}
func (*StateListState) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *StateListState) GetConfig() *stream.Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type StateQuery struct {
	Time int64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
}

func (m *StateQuery) Reset()                    { *m = StateQuery{} }
func (m *StateQuery) String() string            { return proto.CompactTextString(m) }
func (*StateQuery) ProtoMessage()               {}
func (*StateQuery) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func init() {
	proto.RegisterType((*StateContext)(nil), "api.StateContext")
	proto.RegisterType((*StateReport)(nil), "api.StateReport")
	proto.RegisterType((*StateList)(nil), "api.StateList")
	proto.RegisterType((*StateListComponent)(nil), "api.StateListComponent")
	proto.RegisterType((*StateListState)(nil), "api.StateListState")
	proto.RegisterType((*StateQuery)(nil), "api.StateQuery")
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/reporter/api/reporter.proto", fileDescriptor1)
}

var fileDescriptor1 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x69, 0x57, 0xaa, 0x9d, 0x4a, 0x0f, 0xf1, 0xe0, 0x2a, 0x0a, 0x25, 0x07, 0x29, 0x08,
	0x59, 0x69, 0x0f, 0x7e, 0x80, 0x0a, 0xa2, 0xf4, 0x62, 0xc4, 0x73, 0x49, 0xb7, 0x69, 0x8d, 0x90,
	0x3f, 0x24, 0x53, 0xd0, 0x6f, 0x2f, 0x3b, 0xdb, 0xdd, 0x5a, 0xd4, 0x5b, 0xf2, 0xde, 0xcb, 0x6f,
	0x67, 0xde, 0xc2, 0x74, 0x63, 0xf0, 0x7d, 0xbb, 0x14, 0xa5, 0xb7, 0xc5, 0x7a, 0x9b, 0x74, 0xf4,
	0x4b, 0x8f, 0xa6, 0x4c, 0x45, 0xd4, 0xc1, 0x47, 0xd4, 0xb1, 0x50, 0xc1, 0xb4, 0x17, 0x11, 0xa2,
	0x47, 0xcf, 0x32, 0x15, 0xcc, 0xe5, 0xdd, 0x7f, 0x2f, 0x13, 0x2a, 0xd4, 0x09, 0xa3, 0x56, 0xb6,
	0x28, 0xbd, 0x5b, 0x9b, 0x4d, 0xfd, 0x8c, 0x3f, 0xc2, 0xe9, 0x6b, 0xe5, 0xcd, 0xbc, 0x43, 0xfd,
	0x89, 0xec, 0x0a, 0xfa, 0xa5, 0xb7, 0xc1, 0x3b, 0xed, 0x30, 0xef, 0x8c, 0x3a, 0xe3, 0xbe, 0xdc,
	0x0b, 0xec, 0x02, 0x4e, 0x88, 0xb4, 0x30, 0xab, 0xbc, 0x4b, 0xe6, 0x31, 0xdd, 0x9f, 0x56, 0xfc,
	0x19, 0x06, 0x04, 0x92, 0x34, 0x16, 0xbb, 0x06, 0xf8, 0x48, 0xde, 0x2d, 0xc8, 0x6e, 0x40, 0x95,
	0x42, 0xa1, 0xea, 0x33, 0x68, 0xac, 0x4e, 0xa8, 0x6c, 0x20, 0x52, 0x26, 0xf7, 0x02, 0x7f, 0x80,
	0x3e, 0xc5, 0xe6, 0x26, 0x21, 0xbb, 0x07, 0x68, 0x07, 0x48, 0x79, 0x67, 0x94, 0x8d, 0x07, 0x93,
	0x73, 0xa1, 0x82, 0x11, 0x6d, 0x66, 0xd6, 0xf8, 0xf2, 0x47, 0x94, 0xbf, 0x01, 0xfb, 0x9d, 0x60,
	0x0c, 0x8e, 0x9c, 0xb2, 0xcd, 0x48, 0x74, 0x66, 0xb7, 0xd0, 0xab, 0x0b, 0xca, 0xbb, 0x84, 0x3f,
	0x3b, 0xc4, 0xd7, 0x7b, 0xed, 0x22, 0x7c, 0x0e, 0xc3, 0x43, 0xe7, 0x4f, 0xe4, 0x0d, 0xf4, 0xea,
	0x9e, 0x69, 0xbb, 0xc1, 0x64, 0x28, 0xea, 0xf6, 0xc5, 0x8c, 0x54, 0xb9, 0x73, 0xf9, 0x08, 0x80,
	0x20, 0x2f, 0x5b, 0x1d, 0xbf, 0x2a, 0x52, 0xd5, 0x02, 0x91, 0x32, 0x49, 0xe7, 0x65, 0x8f, 0x7e,
	0xd4, 0xf4, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x2a, 0x7f, 0xf8, 0x16, 0x02, 0x00, 0x00,
}
