// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/reporter/view/view-service.proto
// DO NOT EDIT!

/*
Package view is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/reporter/view/view-service.proto
	github.com/fuserobotics/reporter/view/view.proto

It has these top-level messages:
	ListStatesRequest
	ListStatesResponse
	GetStateRequest
	GetStateResponse
	StateHistoryRequest
	StateHistoryResponse
	BoundedStateHistoryRequest
	BoundedStateHistoryResponse
	StateContext
	StateList
	StateListComponent
	StateListState
	StateQuery
	StateHistoryQuery
	StateReport
	StateEntry
*/
package view

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import stream "github.com/fuserobotics/statestream"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StateHistoryResponse_StateHistoryStatus int32

const (
	StateHistoryResponse_HISTORY_INITIAL_SET StateHistoryResponse_StateHistoryStatus = 0
	StateHistoryResponse_HISTORY_TAIL        StateHistoryResponse_StateHistoryStatus = 1
)

var StateHistoryResponse_StateHistoryStatus_name = map[int32]string{
	0: "HISTORY_INITIAL_SET",
	1: "HISTORY_TAIL",
}
var StateHistoryResponse_StateHistoryStatus_value = map[string]int32{
	"HISTORY_INITIAL_SET": 0,
	"HISTORY_TAIL":        1,
}

func (x StateHistoryResponse_StateHistoryStatus) String() string {
	return proto.EnumName(StateHistoryResponse_StateHistoryStatus_name, int32(x))
}
func (StateHistoryResponse_StateHistoryStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

type BoundedStateHistoryRequest_BoundedStateHistoryMode int32

const (
	BoundedStateHistoryRequest_SNAPSHOT_BOUND BoundedStateHistoryRequest_BoundedStateHistoryMode = 0
)

var BoundedStateHistoryRequest_BoundedStateHistoryMode_name = map[int32]string{
	0: "SNAPSHOT_BOUND",
}
var BoundedStateHistoryRequest_BoundedStateHistoryMode_value = map[string]int32{
	"SNAPSHOT_BOUND": 0,
}

func (x BoundedStateHistoryRequest_BoundedStateHistoryMode) String() string {
	return proto.EnumName(BoundedStateHistoryRequest_BoundedStateHistoryMode_name, int32(x))
}
func (BoundedStateHistoryRequest_BoundedStateHistoryMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

type BoundedStateHistoryResponse_BoundedStateHistoryStatus int32

const (
	BoundedStateHistoryResponse_BOUNDED_HISTORY_STATUS_NONE BoundedStateHistoryResponse_BoundedStateHistoryStatus = 0
	BoundedStateHistoryResponse_BOUNDED_HISTORY_START_BOUND BoundedStateHistoryResponse_BoundedStateHistoryStatus = 1
	BoundedStateHistoryResponse_BOUNDED_HISTORY_END_BOUND   BoundedStateHistoryResponse_BoundedStateHistoryStatus = 2
	BoundedStateHistoryResponse_BOUNDED_HISTORY_INITIAL_SET BoundedStateHistoryResponse_BoundedStateHistoryStatus = 3
	BoundedStateHistoryResponse_BOUNDED_HISTORY_TAIL        BoundedStateHistoryResponse_BoundedStateHistoryStatus = 4
)

var BoundedStateHistoryResponse_BoundedStateHistoryStatus_name = map[int32]string{
	0: "BOUNDED_HISTORY_STATUS_NONE",
	1: "BOUNDED_HISTORY_START_BOUND",
	2: "BOUNDED_HISTORY_END_BOUND",
	3: "BOUNDED_HISTORY_INITIAL_SET",
	4: "BOUNDED_HISTORY_TAIL",
}
var BoundedStateHistoryResponse_BoundedStateHistoryStatus_value = map[string]int32{
	"BOUNDED_HISTORY_STATUS_NONE": 0,
	"BOUNDED_HISTORY_START_BOUND": 1,
	"BOUNDED_HISTORY_END_BOUND":   2,
	"BOUNDED_HISTORY_INITIAL_SET": 3,
	"BOUNDED_HISTORY_TAIL":        4,
}

func (x BoundedStateHistoryResponse_BoundedStateHistoryStatus) String() string {
	return proto.EnumName(BoundedStateHistoryResponse_BoundedStateHistoryStatus_name, int32(x))
}
func (BoundedStateHistoryResponse_BoundedStateHistoryStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 0}
}

type ListStatesRequest struct {
}

func (m *ListStatesRequest) Reset()                    { *m = ListStatesRequest{} }
func (m *ListStatesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListStatesRequest) ProtoMessage()               {}
func (*ListStatesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ListStatesResponse struct {
	List *StateList `protobuf:"bytes,1,opt,name=list" json:"list,omitempty"`
}

func (m *ListStatesResponse) Reset()                    { *m = ListStatesResponse{} }
func (m *ListStatesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListStatesResponse) ProtoMessage()               {}
func (*ListStatesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListStatesResponse) GetList() *StateList {
	if m != nil {
		return m.List
	}
	return nil
}

type GetStateRequest struct {
	Context *StateContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Query   *StateQuery   `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
}

func (m *GetStateRequest) Reset()                    { *m = GetStateRequest{} }
func (m *GetStateRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStateRequest) ProtoMessage()               {}
func (*GetStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetStateRequest) GetContext() *StateContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *GetStateRequest) GetQuery() *StateQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

type GetStateResponse struct {
	State *StateReport `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
}

func (m *GetStateResponse) Reset()                    { *m = GetStateResponse{} }
func (m *GetStateResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStateResponse) ProtoMessage()               {}
func (*GetStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetStateResponse) GetState() *StateReport {
	if m != nil {
		return m.State
	}
	return nil
}

type StateHistoryRequest struct {
	Context *StateContext      `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Query   *StateHistoryQuery `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
	// Optionally specify a stream config to do batching on the server
	StreamConfig *stream.Config `protobuf:"bytes,3,opt,name=stream_config,json=streamConfig" json:"stream_config,omitempty"`
}

func (m *StateHistoryRequest) Reset()                    { *m = StateHistoryRequest{} }
func (m *StateHistoryRequest) String() string            { return proto.CompactTextString(m) }
func (*StateHistoryRequest) ProtoMessage()               {}
func (*StateHistoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StateHistoryRequest) GetContext() *StateContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *StateHistoryRequest) GetQuery() *StateHistoryQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *StateHistoryRequest) GetStreamConfig() *stream.Config {
	if m != nil {
		return m.StreamConfig
	}
	return nil
}

// Response in stream of state history.
// Messages will look like:
//  - status: 0, state: {state} (etc)
//  ! (stream closed here if not tailing)
//  - status: 1, state: nil (indicating end of initial set)
//  - status: 1, state: {latest tailed state}
type StateHistoryResponse struct {
	State  *StateEntry                             `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	Status StateHistoryResponse_StateHistoryStatus `protobuf:"varint,2,opt,name=status,enum=view.StateHistoryResponse_StateHistoryStatus" json:"status,omitempty"`
}

func (m *StateHistoryResponse) Reset()                    { *m = StateHistoryResponse{} }
func (m *StateHistoryResponse) String() string            { return proto.CompactTextString(m) }
func (*StateHistoryResponse) ProtoMessage()               {}
func (*StateHistoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StateHistoryResponse) GetState() *StateEntry {
	if m != nil {
		return m.State
	}
	return nil
}

type BoundedStateHistoryRequest struct {
	Context      *StateContext                                      `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Mode         BoundedStateHistoryRequest_BoundedStateHistoryMode `protobuf:"varint,2,opt,name=mode,enum=view.BoundedStateHistoryRequest_BoundedStateHistoryMode" json:"mode,omitempty"`
	MidTimestamp int64                                              `protobuf:"varint,3,opt,name=mid_timestamp,json=midTimestamp" json:"mid_timestamp,omitempty"`
}

func (m *BoundedStateHistoryRequest) Reset()                    { *m = BoundedStateHistoryRequest{} }
func (m *BoundedStateHistoryRequest) String() string            { return proto.CompactTextString(m) }
func (*BoundedStateHistoryRequest) ProtoMessage()               {}
func (*BoundedStateHistoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BoundedStateHistoryRequest) GetContext() *StateContext {
	if m != nil {
		return m.Context
	}
	return nil
}

type BoundedStateHistoryResponse struct {
	State  *StateEntry                                           `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	Status BoundedStateHistoryResponse_BoundedStateHistoryStatus `protobuf:"varint,2,opt,name=status,enum=view.BoundedStateHistoryResponse_BoundedStateHistoryStatus" json:"status,omitempty"`
}

func (m *BoundedStateHistoryResponse) Reset()                    { *m = BoundedStateHistoryResponse{} }
func (m *BoundedStateHistoryResponse) String() string            { return proto.CompactTextString(m) }
func (*BoundedStateHistoryResponse) ProtoMessage()               {}
func (*BoundedStateHistoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BoundedStateHistoryResponse) GetState() *StateEntry {
	if m != nil {
		return m.State
	}
	return nil
}

func init() {
	proto.RegisterType((*ListStatesRequest)(nil), "view.ListStatesRequest")
	proto.RegisterType((*ListStatesResponse)(nil), "view.ListStatesResponse")
	proto.RegisterType((*GetStateRequest)(nil), "view.GetStateRequest")
	proto.RegisterType((*GetStateResponse)(nil), "view.GetStateResponse")
	proto.RegisterType((*StateHistoryRequest)(nil), "view.StateHistoryRequest")
	proto.RegisterType((*StateHistoryResponse)(nil), "view.StateHistoryResponse")
	proto.RegisterType((*BoundedStateHistoryRequest)(nil), "view.BoundedStateHistoryRequest")
	proto.RegisterType((*BoundedStateHistoryResponse)(nil), "view.BoundedStateHistoryResponse")
	proto.RegisterEnum("view.StateHistoryResponse_StateHistoryStatus", StateHistoryResponse_StateHistoryStatus_name, StateHistoryResponse_StateHistoryStatus_value)
	proto.RegisterEnum("view.BoundedStateHistoryRequest_BoundedStateHistoryMode", BoundedStateHistoryRequest_BoundedStateHistoryMode_name, BoundedStateHistoryRequest_BoundedStateHistoryMode_value)
	proto.RegisterEnum("view.BoundedStateHistoryResponse_BoundedStateHistoryStatus", BoundedStateHistoryResponse_BoundedStateHistoryStatus_name, BoundedStateHistoryResponse_BoundedStateHistoryStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ReporterService service

type ReporterServiceClient interface {
	ListStates(ctx context.Context, in *ListStatesRequest, opts ...grpc.CallOption) (*ListStatesResponse, error)
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	GetStateHistory(ctx context.Context, in *StateHistoryRequest, opts ...grpc.CallOption) (ReporterService_GetStateHistoryClient, error)
	GetBoundedStateHistory(ctx context.Context, in *BoundedStateHistoryRequest, opts ...grpc.CallOption) (ReporterService_GetBoundedStateHistoryClient, error)
}

type reporterServiceClient struct {
	cc *grpc.ClientConn
}

func NewReporterServiceClient(cc *grpc.ClientConn) ReporterServiceClient {
	return &reporterServiceClient{cc}
}

func (c *reporterServiceClient) ListStates(ctx context.Context, in *ListStatesRequest, opts ...grpc.CallOption) (*ListStatesResponse, error) {
	out := new(ListStatesResponse)
	err := grpc.Invoke(ctx, "/view.ReporterService/ListStates", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	out := new(GetStateResponse)
	err := grpc.Invoke(ctx, "/view.ReporterService/GetState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterServiceClient) GetStateHistory(ctx context.Context, in *StateHistoryRequest, opts ...grpc.CallOption) (ReporterService_GetStateHistoryClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ReporterService_serviceDesc.Streams[0], c.cc, "/view.ReporterService/GetStateHistory", opts...)
	if err != nil {
		return nil, err
	}
	x := &reporterServiceGetStateHistoryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReporterService_GetStateHistoryClient interface {
	Recv() (*StateHistoryResponse, error)
	grpc.ClientStream
}

type reporterServiceGetStateHistoryClient struct {
	grpc.ClientStream
}

func (x *reporterServiceGetStateHistoryClient) Recv() (*StateHistoryResponse, error) {
	m := new(StateHistoryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *reporterServiceClient) GetBoundedStateHistory(ctx context.Context, in *BoundedStateHistoryRequest, opts ...grpc.CallOption) (ReporterService_GetBoundedStateHistoryClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ReporterService_serviceDesc.Streams[1], c.cc, "/view.ReporterService/GetBoundedStateHistory", opts...)
	if err != nil {
		return nil, err
	}
	x := &reporterServiceGetBoundedStateHistoryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReporterService_GetBoundedStateHistoryClient interface {
	Recv() (*BoundedStateHistoryResponse, error)
	grpc.ClientStream
}

type reporterServiceGetBoundedStateHistoryClient struct {
	grpc.ClientStream
}

func (x *reporterServiceGetBoundedStateHistoryClient) Recv() (*BoundedStateHistoryResponse, error) {
	m := new(BoundedStateHistoryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ReporterService service

type ReporterServiceServer interface {
	ListStates(context.Context, *ListStatesRequest) (*ListStatesResponse, error)
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	GetStateHistory(*StateHistoryRequest, ReporterService_GetStateHistoryServer) error
	GetBoundedStateHistory(*BoundedStateHistoryRequest, ReporterService_GetBoundedStateHistoryServer) error
}

func RegisterReporterServiceServer(s *grpc.Server, srv ReporterServiceServer) {
	s.RegisterService(&_ReporterService_serviceDesc, srv)
}

func _ReporterService_ListStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServiceServer).ListStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/view.ReporterService/ListStates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServiceServer).ListStates(ctx, req.(*ListStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReporterService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/view.ReporterService/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServiceServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReporterService_GetStateHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StateHistoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReporterServiceServer).GetStateHistory(m, &reporterServiceGetStateHistoryServer{stream})
}

type ReporterService_GetStateHistoryServer interface {
	Send(*StateHistoryResponse) error
	grpc.ServerStream
}

type reporterServiceGetStateHistoryServer struct {
	grpc.ServerStream
}

func (x *reporterServiceGetStateHistoryServer) Send(m *StateHistoryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ReporterService_GetBoundedStateHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BoundedStateHistoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReporterServiceServer).GetBoundedStateHistory(m, &reporterServiceGetBoundedStateHistoryServer{stream})
}

type ReporterService_GetBoundedStateHistoryServer interface {
	Send(*BoundedStateHistoryResponse) error
	grpc.ServerStream
}

type reporterServiceGetBoundedStateHistoryServer struct {
	grpc.ServerStream
}

func (x *reporterServiceGetBoundedStateHistoryServer) Send(m *BoundedStateHistoryResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ReporterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "view.ReporterService",
	HandlerType: (*ReporterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListStates",
			Handler:    _ReporterService_ListStates_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _ReporterService_GetState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStateHistory",
			Handler:       _ReporterService_GetStateHistory_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetBoundedStateHistory",
			Handler:       _ReporterService_GetBoundedStateHistory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/reporter/view/view-service.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 730 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x52, 0x13, 0x4b,
	0x14, 0x66, 0x42, 0xe0, 0xde, 0x3a, 0x37, 0x84, 0x70, 0xe0, 0x42, 0x08, 0x5a, 0xe2, 0x50, 0x85,
	0x2e, 0x4c, 0x86, 0x9f, 0x05, 0x50, 0x54, 0x89, 0x01, 0x22, 0xa4, 0x2a, 0x26, 0x3a, 0x33, 0x2c,
	0x5c, 0x4d, 0xe5, 0xa7, 0x09, 0x53, 0x95, 0x4c, 0x87, 0xe9, 0x0e, 0x4a, 0x59, 0x6c, 0xdc, 0xba,
	0xd4, 0x77, 0xe0, 0x11, 0x7c, 0x03, 0x5f, 0x40, 0x1f, 0xc1, 0xa5, 0x0f, 0x61, 0xa5, 0xbb, 0x87,
	0x4c, 0xfe, 0x44, 0x74, 0x43, 0x31, 0xe7, 0xfb, 0xce, 0xd7, 0xdf, 0xe9, 0x73, 0xfa, 0x04, 0xb6,
	0xeb, 0x2e, 0x3f, 0x6b, 0x57, 0x32, 0x55, 0xda, 0x34, 0x4e, 0xdb, 0x8c, 0xf8, 0xb4, 0x42, 0xb9,
	0x5b, 0x65, 0x86, 0x4f, 0x5a, 0xd4, 0xe7, 0xc4, 0x37, 0x2e, 0x5c, 0xf2, 0x46, 0xfc, 0x49, 0x33,
	0xe2, 0x5f, 0xb8, 0x55, 0x92, 0x69, 0xf9, 0x94, 0x53, 0x8c, 0x76, 0x62, 0xa9, 0x7b, 0x75, 0x4a,
	0xeb, 0x0d, 0x62, 0x94, 0x5b, 0xae, 0x51, 0xf6, 0x3c, 0xca, 0xcb, 0xdc, 0xa5, 0x1e, 0x93, 0x9c,
	0xd4, 0xda, 0xef, 0xab, 0xdf, 0x96, 0xc1, 0x78, 0x99, 0x13, 0xc6, 0x7d, 0x52, 0x6e, 0x1a, 0x55,
	0xea, 0x9d, 0xba, 0x75, 0x99, 0xa1, 0xcf, 0xc2, 0x4c, 0xc1, 0x65, 0xdc, 0x12, 0xb8, 0x49, 0xce,
	0xdb, 0x84, 0x71, 0x7d, 0x07, 0x30, 0x1c, 0x64, 0x2d, 0xea, 0x31, 0x82, 0x2b, 0x10, 0x6d, 0xb8,
	0x8c, 0x27, 0xb5, 0x65, 0xed, 0xf1, 0x7f, 0x1b, 0xd3, 0x19, 0x71, 0xae, 0xe0, 0x74, 0xc8, 0xa6,
	0x00, 0xf5, 0x3a, 0x4c, 0x1f, 0x11, 0x99, 0xa9, 0xd4, 0xf0, 0x09, 0xfc, 0x53, 0xa5, 0x1e, 0x27,
	0x6f, 0x83, 0x54, 0x0c, 0xa5, 0x1e, 0x48, 0xc4, 0x0c, 0x28, 0xb8, 0x0a, 0x13, 0xe7, 0x6d, 0xe2,
	0x5f, 0x26, 0x23, 0x82, 0x9b, 0x08, 0x71, 0x5f, 0x75, 0xe2, 0xa6, 0x84, 0xf5, 0x5d, 0x48, 0x74,
	0x0f, 0x52, 0x0e, 0x1f, 0xc1, 0x84, 0x28, 0x54, 0x9d, 0x33, 0x13, 0xca, 0x35, 0xc5, 0x95, 0x99,
	0x12, 0xd7, 0xaf, 0x35, 0x98, 0x15, 0xe1, 0x63, 0x97, 0x71, 0xea, 0x5f, 0xfe, 0x99, 0xd5, 0x74,
	0xaf, 0xd5, 0x85, 0x10, 0x57, 0xe9, 0x86, 0x1d, 0xe3, 0x26, 0x4c, 0xc9, 0x0e, 0x38, 0xb2, 0x03,
	0xc9, 0x71, 0x91, 0x16, 0xcf, 0xc8, 0x68, 0xe6, 0x40, 0x44, 0xcd, 0x98, 0xfc, 0x94, 0x5f, 0xfa,
	0x17, 0x0d, 0xe6, 0x7a, 0x9d, 0xaa, 0x5a, 0x57, 0x7b, 0x6b, 0x0d, 0xdf, 0x53, 0xce, 0xe3, 0x9d,
	0x53, 0x05, 0x8c, 0x39, 0x98, 0xec, 0xfc, 0xd3, 0x66, 0xc2, 0x65, 0x7c, 0x23, 0x3d, 0xe8, 0x32,
	0xd0, 0xec, 0x09, 0x5a, 0x22, 0xc9, 0x54, 0xc9, 0xfa, 0x1e, 0xe0, 0x20, 0x8a, 0x0b, 0x30, 0x7b,
	0x9c, 0xb7, 0xec, 0x92, 0xf9, 0xda, 0xc9, 0x17, 0xf3, 0x76, 0x3e, 0x5b, 0x70, 0xac, 0x9c, 0x9d,
	0x18, 0xc3, 0x04, 0xc4, 0x02, 0xc0, 0xce, 0xe6, 0x0b, 0x09, 0x4d, 0xff, 0xa1, 0x41, 0x6a, 0x9f,
	0xb6, 0xbd, 0x1a, 0xa9, 0xfd, 0xfd, 0xcd, 0x17, 0x20, 0xda, 0xa4, 0x35, 0xa2, 0x4a, 0xda, 0x96,
	0xd4, 0xd1, 0xea, 0xc3, 0xa0, 0x17, 0xb4, 0x46, 0x4c, 0xa1, 0x82, 0x2b, 0x30, 0xd5, 0x74, 0x6b,
	0x0e, 0x77, 0x9b, 0x84, 0xf1, 0x72, 0xb3, 0x25, 0x1a, 0x33, 0x6e, 0xc6, 0x9a, 0x6e, 0xcd, 0x0e,
	0x62, 0x7a, 0x1a, 0x16, 0x46, 0xa8, 0x20, 0x42, 0xdc, 0x2a, 0x66, 0x5f, 0x5a, 0xc7, 0x25, 0xdb,
	0xd9, 0x2f, 0x9d, 0x14, 0x0f, 0x13, 0x63, 0xfa, 0xb7, 0x08, 0x2c, 0x0d, 0x35, 0x74, 0xc7, 0xf6,
	0x59, 0x7d, 0xed, 0xdb, 0xfd, 0x45, 0xad, 0xaa, 0x8b, 0x43, 0xb0, 0xbe, 0x66, 0x7e, 0xd6, 0x60,
	0x71, 0x24, 0x0b, 0x1f, 0xc0, 0x92, 0xa8, 0x22, 0x77, 0xe8, 0x04, 0x3d, 0xb4, 0xec, 0xac, 0x7d,
	0x62, 0x39, 0xc5, 0x52, 0x31, 0x97, 0x18, 0x1b, 0x41, 0x30, 0x83, 0xe2, 0x35, 0xbc, 0x0f, 0x8b,
	0xfd, 0x84, 0x5c, 0xf1, 0x50, 0xc1, 0x91, 0x61, 0xf9, 0xe1, 0xe9, 0x19, 0xc7, 0x24, 0xcc, 0xf5,
	0x13, 0xc4, 0x14, 0x45, 0x37, 0x3e, 0x45, 0x61, 0xda, 0x54, 0xdb, 0xcf, 0x92, 0x0b, 0x15, 0x4f,
	0x00, 0xba, 0xdb, 0x0a, 0xd5, 0x2b, 0x1c, 0x58, 0x6a, 0xa9, 0xe4, 0x20, 0x20, 0x2f, 0x4c, 0x9f,
	0x7b, 0xff, 0xf5, 0xfb, 0xc7, 0x48, 0x1c, 0x63, 0xc6, 0xc5, 0xba, 0x5c, 0xa9, 0xe5, 0x46, 0x03,
	0x7d, 0xf8, 0x37, 0x58, 0x30, 0xf8, 0xbf, 0xcc, 0xed, 0xdb, 0x6c, 0xa9, 0xf9, 0xfe, 0xb0, 0x12,
	0xdc, 0x12, 0x82, 0xeb, 0x68, 0xdc, 0x08, 0xbe, 0x53, 0x93, 0xdb, 0xd9, 0xcc, 0x2d, 0xea, 0x11,
	0x8f, 0x5f, 0x75, 0x63, 0xa2, 0xd3, 0x8e, 0x5b, 0xbb, 0xc2, 0x0f, 0x5a, 0x77, 0x7d, 0xaa, 0xa6,
	0xe0, 0xe2, 0xb0, 0x07, 0x2b, 0xcf, 0x4f, 0x8d, 0x7e, 0xcb, 0xfa, 0x9e, 0xf0, 0xb0, 0x83, 0x5b,
	0x77, 0xf4, 0x60, 0x9c, 0x49, 0xa1, 0x35, 0x0d, 0xaf, 0x35, 0x98, 0x3f, 0x22, 0x7c, 0xc8, 0xa4,
	0xe0, 0xf2, 0x6d, 0x4f, 0x2e, 0xf5, 0xf0, 0xd6, 0x41, 0xd5, 0x9f, 0x0b, 0x8b, 0xcf, 0xf0, 0xe9,
	0x5d, 0x2d, 0x56, 0xa4, 0xe8, 0x8d, 0xd3, 0xca, 0xa4, 0xf8, 0x31, 0xdb, 0xfc, 0x19, 0x00, 0x00,
	0xff, 0xff, 0xa7, 0x92, 0xfa, 0x37, 0x90, 0x07, 0x00, 0x00,
}
