// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/reporter/view/view.proto
// DO NOT EDIT!

package view

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import stream "github.com/fuserobotics/statestream"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StateContext struct {
	HostIdentifier string `protobuf:"bytes,1,opt,name=host_identifier,json=hostIdentifier" json:"host_identifier,omitempty"`
	Component      string `protobuf:"bytes,2,opt,name=component" json:"component,omitempty"`
	StateId        string `protobuf:"bytes,3,opt,name=state_id,json=stateId" json:"state_id,omitempty"`
}

func (m *StateContext) Reset()                    { *m = StateContext{} }
func (m *StateContext) String() string            { return proto.CompactTextString(m) }
func (*StateContext) ProtoMessage()               {}
func (*StateContext) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type StateList struct {
	Components []*StateListComponent `protobuf:"bytes,1,rep,name=components" json:"components,omitempty"`
}

func (m *StateList) Reset()                    { *m = StateList{} }
func (m *StateList) String() string            { return proto.CompactTextString(m) }
func (*StateList) ProtoMessage()               {}
func (*StateList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *StateList) GetComponents() []*StateListComponent {
	if m != nil {
		return m.Components
	}
	return nil
}

type StateListComponent struct {
	Name           string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	States         []*StateListState `protobuf:"bytes,2,rep,name=states" json:"states,omitempty"`
	HostIdentifier string            `protobuf:"bytes,3,opt,name=host_identifier,json=hostIdentifier" json:"host_identifier,omitempty"`
}

func (m *StateListComponent) Reset()                    { *m = StateListComponent{} }
func (m *StateListComponent) String() string            { return proto.CompactTextString(m) }
func (*StateListComponent) ProtoMessage()               {}
func (*StateListComponent) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *StateListComponent) GetStates() []*StateListState {
	if m != nil {
		return m.States
	}
	return nil
}

type StateListState struct {
	Name   string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Config *stream.Config `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
}

func (m *StateListState) Reset()                    { *m = StateListState{} }
func (m *StateListState) String() string            { return proto.CompactTextString(m) }
func (*StateListState) ProtoMessage()               {}
func (*StateListState) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *StateListState) GetConfig() *stream.Config {
	if m != nil {
		return m.Config
	}
	return nil
}

// Query a specific time.
type StateQuery struct {
	Time int64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
}

func (m *StateQuery) Reset()                    { *m = StateQuery{} }
func (m *StateQuery) String() string            { return proto.CompactTextString(m) }
func (*StateQuery) ProtoMessage()               {}
func (*StateQuery) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

// Query a range of time.
type StateHistoryQuery struct {
	// Begin time, or the entire history if zero.
	BeginTime int64 `protobuf:"varint,1,opt,name=begin_time,json=beginTime" json:"begin_time,omitempty"`
	// End time, or latest if zero.
	EndTime int64 `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	// If end_time == 0 and tail == true then tail entries.
	Tail bool `protobuf:"varint,3,opt,name=tail" json:"tail,omitempty"`
}

func (m *StateHistoryQuery) Reset()                    { *m = StateHistoryQuery{} }
func (m *StateHistoryQuery) String() string            { return proto.CompactTextString(m) }
func (*StateHistoryQuery) ProtoMessage()               {}
func (*StateHistoryQuery) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

// A state report message
type StateReport struct {
	JsonState string `protobuf:"bytes,1,opt,name=json_state,json=jsonState" json:"json_state,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *StateReport) Reset()                    { *m = StateReport{} }
func (m *StateReport) String() string            { return proto.CompactTextString(m) }
func (*StateReport) ProtoMessage()               {}
func (*StateReport) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

// A state entry message
type StateEntry struct {
	JsonState string `protobuf:"bytes,1,opt,name=json_state,json=jsonState" json:"json_state,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Type      int32  `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
}

func (m *StateEntry) Reset()                    { *m = StateEntry{} }
func (m *StateEntry) String() string            { return proto.CompactTextString(m) }
func (*StateEntry) ProtoMessage()               {}
func (*StateEntry) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func init() {
	proto.RegisterType((*StateContext)(nil), "view.StateContext")
	proto.RegisterType((*StateList)(nil), "view.StateList")
	proto.RegisterType((*StateListComponent)(nil), "view.StateListComponent")
	proto.RegisterType((*StateListState)(nil), "view.StateListState")
	proto.RegisterType((*StateQuery)(nil), "view.StateQuery")
	proto.RegisterType((*StateHistoryQuery)(nil), "view.StateHistoryQuery")
	proto.RegisterType((*StateReport)(nil), "view.StateReport")
	proto.RegisterType((*StateEntry)(nil), "view.StateEntry")
}

func init() { proto.RegisterFile("github.com/fuserobotics/reporter/view/view.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0xaf, 0xd3, 0x30,
	0x10, 0x54, 0x9b, 0x47, 0xdf, 0xcb, 0x16, 0x15, 0x61, 0x71, 0x08, 0xa8, 0x48, 0x95, 0x0f, 0xd0,
	0x03, 0x4a, 0x50, 0xb9, 0x70, 0xaf, 0x2a, 0x51, 0xd4, 0x0b, 0x81, 0x2b, 0x8a, 0xf2, 0xb1, 0x6d,
	0x8d, 0x88, 0x1d, 0xd9, 0x5b, 0xa0, 0x27, 0xfe, 0x3a, 0xf2, 0x3a, 0xb4, 0x05, 0xca, 0xe5, 0x5d,
	0xa2, 0xcd, 0xec, 0x78, 0x76, 0x67, 0x6c, 0x78, 0xbd, 0x53, 0xb4, 0x3f, 0x54, 0x69, 0x6d, 0xda,
	0x6c, 0x7b, 0x70, 0x68, 0x4d, 0x65, 0x48, 0xd5, 0x2e, 0xb3, 0xd8, 0x19, 0x4b, 0x68, 0xb3, 0x6f,
	0x0a, 0xbf, 0xf3, 0x27, 0xed, 0xac, 0x21, 0x23, 0x6e, 0x7c, 0xfd, 0xec, 0xbf, 0xe7, 0x1c, 0x95,
	0x84, 0x8e, 0x2c, 0x96, 0x6d, 0x56, 0x1b, 0xbd, 0x55, 0xbb, 0x70, 0x4e, 0x76, 0xf0, 0xf0, 0xa3,
	0xef, 0x2d, 0x8d, 0x26, 0xfc, 0x41, 0xe2, 0x25, 0x3c, 0xda, 0x1b, 0x47, 0x85, 0x6a, 0x50, 0x93,
	0xda, 0x2a, 0xb4, 0xc9, 0x60, 0x36, 0x98, 0xc7, 0xf9, 0xc4, 0xc3, 0xeb, 0x13, 0x2a, 0xa6, 0x10,
	0xd7, 0xa6, 0xed, 0x8c, 0x46, 0x4d, 0xc9, 0x90, 0x29, 0x67, 0x40, 0x3c, 0x85, 0x3b, 0x1e, 0x59,
	0xa8, 0x26, 0x89, 0xb8, 0x79, 0xcb, 0xff, 0xeb, 0x46, 0xae, 0x20, 0xe6, 0x89, 0x1b, 0xe5, 0x48,
	0xbc, 0x05, 0x38, 0x1d, 0x72, 0xc9, 0x60, 0x16, 0xcd, 0xc7, 0x8b, 0x24, 0x65, 0x5f, 0x27, 0xd2,
	0xf2, 0x37, 0x21, 0xbf, 0xe0, 0xca, 0x9f, 0x20, 0xfe, 0x65, 0x08, 0x01, 0x37, 0xba, 0x6c, 0xb1,
	0xdf, 0x99, 0x6b, 0xf1, 0x0a, 0x46, 0xc1, 0x7e, 0x32, 0x64, 0xfd, 0x27, 0x7f, 0xe9, 0x73, 0x91,
	0xf7, 0x9c, 0x6b, 0x01, 0x44, 0xd7, 0x02, 0x90, 0x1b, 0x98, 0xfc, 0x29, 0x71, 0x75, 0xf8, 0x0b,
	0x18, 0x85, 0xbc, 0x39, 0xa3, 0xf1, 0x62, 0x92, 0x86, 0x5b, 0x48, 0x97, 0x8c, 0xe6, 0x7d, 0x57,
	0xce, 0x00, 0x58, 0xe4, 0xc3, 0x01, 0xed, 0xd1, 0x2b, 0x91, 0xea, 0x95, 0xa2, 0x9c, 0x6b, 0x59,
	0xc2, 0x63, 0x66, 0xbc, 0x53, 0x8e, 0x8c, 0x3d, 0x06, 0xe2, 0x73, 0x80, 0x0a, 0x77, 0x4a, 0x17,
	0x17, 0xf4, 0x98, 0x91, 0x4f, 0xaa, 0x45, 0x7f, 0x0d, 0xa8, 0x9b, 0xd0, 0x1c, 0x72, 0xf3, 0x16,
	0x75, 0xc3, 0x2d, 0x3f, 0xa2, 0x54, 0x5f, 0xd9, 0xdc, 0x5d, 0xce, 0xb5, 0x7c, 0x0f, 0xe3, 0x10,
	0x06, 0xbf, 0x32, 0x2f, 0xfe, 0xc5, 0x19, 0x5d, 0x70, 0x32, 0xbd, 0xab, 0xd8, 0x23, 0xc1, 0xee,
	0x14, 0x62, 0x2f, 0xec, 0xa8, 0x6c, 0xbb, 0x5e, 0xfd, 0x0c, 0xc8, 0xcf, 0xbd, 0xa1, 0x95, 0xa6,
	0xb0, 0xe7, 0xbd, 0xa5, 0x78, 0xd5, 0x63, 0x87, 0xbc, 0xea, 0x83, 0x9c, 0xeb, 0x6a, 0xc4, 0xcf,
	0xf7, 0xcd, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0x3d, 0x14, 0x8e, 0x2a, 0x03, 0x00, 0x00,
}
